trigger:
  branches:
    include:
      - main

variables:
  appName: app-portfolio-dev

steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'SERVICE_CONNECTION_NAME'
      appType: 'webAppLinux'
      appName: '$(appName)'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
