version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - cd terraform
      - terraform init -input=false -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=$TF_STATE_KEY" -backend-config="region=$AWS_DEFAULT_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
      - terraform apply -input=false -auto-approve tfplan
