from pathlib import Path
import json

base = Path('infrastructure/bicep/azure')

module_defs = {
    'ai-search': {
        'title': 'Azure Cognitive Search',
        'description': 'Deploys an Azure Cognitive Search service for indexing and search workloads.',
        'resource_type': 'Microsoft.Search/searchServices',
        'api_version': '2023-05-01',
        'params': [
            ('searchServiceName', 'string', 'search-portfolio', 'Search service name'),
            ('skuName', 'string', 'standard', 'Search service SKU'),
            ('replicaCount', 'int', 1, 'Number of replicas'),
            ('partitionCount', 'int', 1, 'Number of partitions'),
        ],
        'outputs': [('searchServiceId', 'string', 'searchService.id')],
    },
    'azure-openai': {
        'title': 'Azure OpenAI Service',
        'description': 'Deploys an Azure OpenAI resource for generative AI workloads.',
        'resource_type': 'Microsoft.CognitiveServices/accounts',
        'api_version': '2021-10-01',
        'properties': {
            'kind': 'OpenAI',
            'sku': 'S0',
        },
        'params': [
            ('accountName', 'string', 'openai-portfolio', 'OpenAI account name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('accountId', 'string', 'openAiAccount.id')],
    },
    'bot-service': {
        'title': 'Azure Bot Service',
        'description': 'Deploys an Azure Bot Service resource for conversational applications.',
        'resource_type': 'Microsoft.BotService/botServices',
        'api_version': '2021-05-01',
        'params': [
            ('botName', 'string', 'bot-portfolio', 'Bot service name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('appId', 'string', '', 'Application (client) ID for the bot'),
        ],
        'outputs': [('botId', 'string', 'bot.id')],
    },
    'cognitive-services-account': {
        'title': 'Cognitive Services Account',
        'description': 'Deploys an Azure Cognitive Services account for AI workloads.',
        'resource_type': 'Microsoft.CognitiveServices/accounts',
        'api_version': '2021-10-01',
        'properties': {'kind': 'CognitiveServices', 'sku': 'S0'},
        'params': [
            ('accountName', 'string', 'cogsvc-portfolio', 'Cognitive Services account name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('accountId', 'string', 'cogService.id')],
    },
    'document-intelligence': {
        'title': 'Document Intelligence',
        'description': 'Deploys a Document Intelligence resource for form and document processing.',
        'resource_type': 'Microsoft.CognitiveServices/accounts',
        'api_version': '2021-10-01',
        'properties': {'kind': 'FormRecognizer', 'sku': 'S0'},
        'params': [
            ('accountName', 'string', 'docintel-portfolio', 'Document Intelligence account name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('resourceId', 'string', 'docIntelligence.id')],
    },
    'language-service': {
        'title': 'Azure Language Service',
        'description': 'Deploys an Azure Language service resource for natural language workloads.',
        'resource_type': 'Microsoft.CognitiveServices/accounts',
        'api_version': '2021-10-01',
        'properties': {'kind': 'LanguageService', 'sku': 'S1'},
        'params': [
            ('accountName', 'string', 'langsvc-portfolio', 'Language service account name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('resourceId', 'string', 'languageService.id')],
    },
    'machine-learning-workspace': {
        'title': 'Machine Learning Workspace',
        'description': 'Deploys an Azure Machine Learning workspace for ML development and model training.',
        'resource_type': 'Microsoft.MachineLearningServices/workspaces',
        'api_version': '2023-04-01',
        'params': [
            ('workspaceName', 'string', 'mlws-portfolio', 'ML workspace name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('workspaceId', 'string', 'mlWorkspace.id')],
    },
    'speech-service': {
        'title': 'Speech Service',
        'description': 'Deploys an Azure Speech service resource for speech-to-text and text-to-speech.',
        'resource_type': 'Microsoft.CognitiveServices/accounts',
        'api_version': '2021-10-01',
        'properties': {'kind': 'SpeechServices', 'sku': 'S0'},
        'params': [
            ('accountName', 'string', 'speech-portfolio', 'Speech service account name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('serviceId', 'string', 'speechService.id')],
    },
    'aks-cluster': {
        'title': 'AKS Cluster',
        'description': 'Deploys an Azure Kubernetes Service (AKS) cluster for container orchestration.',
        'resource_type': 'Microsoft.ContainerService/managedClusters',
        'api_version': '2024-01-01',
        'properties': {'enableRBAC': True, 'dnsPrefix': 'aks', 'agentPoolProfiles': []},
        'params': [
            ('clusterName', 'string', 'aks-portfolio', 'AKS cluster name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('nodeCount', 'int', 3, 'Default node count'),
            ('nodeVmSize', 'string', 'Standard_DS2_v2', 'Node VM size'),
        ],
        'outputs': [('clusterId', 'string', 'aksCluster.id')],
    },
    'node-pool': {
        'title': 'AKS Node Pool',
        'description': 'Deploys a node pool into an existing AKS cluster.',
        'resource_type': 'Microsoft.ContainerService/managedClusters/agentPools',
        'api_version': '2024-02-01',
        'params': [
            ('clusterName', 'string', 'aks-portfolio', 'Existing AKS cluster name'),
            ('nodePoolName', 'string', 'default', 'AKS node pool name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('count', 'int', 3, 'Number of nodes in the pool'),
        ],
        'name_template': "'${clusterName}/${nodePoolName}'",
        'outputs': [('nodePoolId', 'string', 'nodePool.id')],
    },
    'aks': {
        'title': 'AKS Cluster (Alternate)',
        'description': 'Deploys an Azure Kubernetes Service (AKS) cluster for container orchestration.',
        'resource_type': 'Microsoft.ContainerService/managedClusters',
        'api_version': '2024-01-01',
        'params': [
            ('clusterName', 'string', 'aks-portfolio', 'AKS cluster name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('agentPoolName', 'string', 'agentpool', 'AKS agent pool name'),
        ],
        'outputs': [('clusterId', 'string', 'aksCluster.id')],
    },
    'app-service': {
        'title': 'App Service',
        'description': 'Deploys an Azure App Service web app.',
        'resource_type': 'Microsoft.Web/sites',
        'api_version': '2022-03-01',
        'params': [
            ('appName', 'string', 'app-portfolio', 'App Service name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('servicePlanId', 'string', 'service-plan-id', 'App Service plan resource ID'),
        ],
        'outputs': [('appId', 'string', 'app.id')],
    },
    'app-service-plan': {
        'title': 'App Service Plan',
        'description': 'Deploys an Azure App Service plan for hosting web apps and functions.',
        'resource_type': 'Microsoft.Web/serverfarms',
        'api_version': '2022-03-01',
        'params': [
            ('planName', 'string', 'asp-portfolio', 'App Service plan name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('skuName', 'string', 'P1v2', 'App Service plan SKU'),
        ],
        'outputs': [('planId', 'string', 'appServicePlan.id')],
    },
    'container-app': {
        'title': 'Container App',
        'description': 'Deploys an Azure Container App for containerized workloads.',
        'resource_type': 'Microsoft.App/containerApps',
        'api_version': '2024-01-01-preview',
        'params': [
            ('containerAppName', 'string', 'ca-portfolio', 'Container App name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('environmentId', 'string', 'container-app-env-id', 'Container Apps environment resource ID'),
        ],
        'outputs': [('containerAppId', 'string', 'containerApp.id')],
    },
    'function-app': {
        'title': 'Function App',
        'description': 'Deploys an Azure Function App for serverless workloads.',
        'resource_type': 'Microsoft.Web/sites',
        'api_version': '2022-03-01',
        'properties': {'kind': 'functionapp'},
        'params': [
            ('functionName', 'string', 'func-portfolio', 'Function App name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('servicePlanId', 'string', 'service-plan-id', 'App Service plan resource ID'),
        ],
        'outputs': [('functionId', 'string', 'functionApp.id')],
    },
    'virtual-machine': {
        'title': 'Virtual Machine',
        'description': 'Deploys an Azure Virtual Machine.',
        'resource_type': 'Microsoft.Compute/virtualMachines',
        'api_version': '2024-04-01',
        'params': [
            ('vmName', 'string', 'vm-portfolio', 'Virtual machine name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('vmSize', 'string', 'Standard_DS1_v2', 'VM size'),
        ],
        'outputs': [('vmId', 'string', 'vm.id')],
    },
    'vm-scale-set': {
        'title': 'Virtual Machine Scale Set',
        'description': 'Deploys an Azure Virtual Machine Scale Set.',
        'resource_type': 'Microsoft.Compute/virtualMachineScaleSets',
        'api_version': '2024-04-01',
        'params': [
            ('vmssName', 'string', 'vmss-portfolio', 'Scale set name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('instanceCount', 'int', 2, 'Scale set instance count'),
        ],
        'outputs': [('vmssId', 'string', 'vmss.id')],
    },
    'cosmos-db': {
        'title': 'Cosmos DB Account',
        'description': 'Deploys an Azure Cosmos DB account for globally distributed data stores.',
        'resource_type': 'Microsoft.DocumentDB/databaseAccounts',
        'api_version': '2023-03-15',
        'params': [
            ('accountName', 'string', 'cosmos-portfolio', 'Cosmos DB account name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('databaseName', 'string', 'db1', 'Initial database name'),
        ],
        'outputs': [('accountId', 'string', 'cosmos.id')],
    },
    'data-factory': {
        'title': 'Data Factory',
        'description': 'Deploys an Azure Data Factory instance.',
        'resource_type': 'Microsoft.DataFactory/factories',
        'api_version': '2023-03-01',
        'params': [
            ('factoryName', 'string', 'adf-portfolio', 'Data Factory name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('factoryId', 'string', 'dataFactory.id')],
    },
    'databricks-workspace': {
        'title': 'Databricks Workspace',
        'description': 'Deploys an Azure Databricks workspace.',
        'resource_type': 'Microsoft.Databricks/workspaces',
        'api_version': '2023-04-01',
        'params': [
            ('workspaceName', 'string', 'dbws-portfolio', 'Databricks workspace name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('workspaceId', 'string', 'dbWorkspace.id')],
    },
    'fabric-workspace': {
        'title': 'Fabric Workspace',
        'description': 'Deploys an Azure Fabric workspace for analytics and data workloads.',
        'resource_type': 'Microsoft.Fabric/workspaces',
        'api_version': '2024-01-01-preview',
        'params': [
            ('workspaceName', 'string', 'fabric-portfolio', 'Fabric workspace name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('workspaceId', 'string', 'fabricWorkspace.id')],
    },
    'file-share': {
        'title': 'File Share',
        'description': 'Deploys an Azure Storage file share within an existing storage account.',
        'resource_type': 'Microsoft.Storage/storageAccounts/fileServices/shares',
        'api_version': '2022-09-01',
        'name_template': "'${storageAccountName}/default/${shareName}'",
        'params': [
            ('storageAccountName', 'string', 'stgacctportfolio', 'Storage account name'),
            ('shareName', 'string', 'fileshare', 'File share name'),
        ],
        'outputs': [('shareId', 'string', 'fileShare.id')],
    },
    'postgresql-flexible-server': {
        'title': 'PostgreSQL Flexible Server',
        'description': 'Deploys an Azure Database for PostgreSQL flexible server.',
        'resource_type': 'Microsoft.DBForPostgreSQL/flexibleServers',
        'api_version': '2023-03-01-preview',
        'params': [
            ('serverName', 'string', 'pgflex-portfolio', 'PostgreSQL server name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('administratorLogin', 'string', 'pgadmin', 'Administrator login'),
        ],
        'outputs': [('serverId', 'string', 'pgServer.id')],
    },
    'redis-cache': {
        'title': 'Redis Cache',
        'description': 'Deploys an Azure Redis Cache instance.',
        'resource_type': 'Microsoft.Cache/Redis',
        'api_version': '2023-03-01',
        'params': [
            ('redisName', 'string', 'redis-portfolio', 'Redis cache name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('skuName', 'string', 'Standard', 'Redis SKU name'),
        ],
        'outputs': [('redisId', 'string', 'redis.id')],
    },
    'sql-database': {
        'title': 'SQL Database',
        'description': 'Deploys an Azure SQL Database in a SQL server.',
        'resource_type': 'Microsoft.Sql/servers/databases',
        'api_version': '2022-02-01-preview',
        'name_template': "'${sqlServerName}/${databaseName}'",
        'params': [
            ('sqlServerName', 'string', 'sqlserverportfolio', 'Existing SQL server name'),
            ('databaseName', 'string', 'sqldb', 'SQL database name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('databaseId', 'string', 'sqlDatabase.id')],
    },
    'storage-account': {
        'title': 'Storage Account',
        'description': 'Deploys an Azure Storage account.',
        'resource_type': 'Microsoft.Storage/storageAccounts',
        'api_version': '2023-01-01',
        'params': [
            ('storageAccountName', 'string', 'stgacctportfolio', 'Storage account name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('skuName', 'string', 'Standard_LRS', 'Storage SKU'),
        ],
        'outputs': [('storageAccountId', 'string', 'storageAccount.id')],
    },
    'storage-container': {
        'title': 'Storage Container',
        'description': 'Deploys a blob storage container within an existing storage account.',
        'resource_type': 'Microsoft.Storage/storageAccounts/blobServices/containers',
        'api_version': '2022-09-01',
        'name_template': "'${storageAccountName}/default/${containerName}'",
        'params': [
            ('storageAccountName', 'string', 'stgacctportfolio', 'Storage account name'),
            ('containerName', 'string', 'data', 'Blob container name'),
        ],
        'outputs': [('containerId', 'string', 'container.id')],
    },
    'data-factory': {
        'title': 'Data Factory Instance',
        'description': 'Deploys an Azure Data Factory factory instance.',
        'resource_type': 'Microsoft.DataFactory/factories',
        'api_version': '2023-03-01',
        'params': [
            ('factoryName', 'string', 'adf-portfolio', 'Data Factory name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('factoryId', 'string', 'factory.id')],
    },
    'integration-runtime': {
        'title': 'Data Factory Integration Runtime',
        'description': 'Deploys an Azure Data Factory integration runtime for compute execution.',
        'resource_type': 'Microsoft.DataFactory/factories/integrationRuntimes',
        'api_version': '2023-03-01',
        'name_template': "'${factoryName}/${integrationRuntimeName}'",
        'params': [
            ('factoryName', 'string', 'adf-portfolio', 'Existing Data Factory name'),
            ('integrationRuntimeName', 'string', 'selfhosted', 'Integration Runtime name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('runtimeId', 'string', 'integrationRuntime.id')],
    },
    'managed-private-endpoint': {
        'title': 'Managed Private Endpoint',
        'description': 'Deploys a managed private endpoint in Azure Data Factory.',
        'resource_type': 'Microsoft.DataFactory/factories/managedPrivateEndpoints',
        'api_version': '2023-03-01',
        'name_template': "'${factoryName}/${endpointName}'",
        'params': [
            ('factoryName', 'string', 'adf-portfolio', 'Existing Data Factory name'),
            ('endpointName', 'string', 'mpe-portfolio', 'Managed private endpoint name'),
            ('privateLinkResourceId', 'string', '/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/...', 'Target resource ID'),
        ],
        'outputs': [('endpointId', 'string', 'managedPrivateEndpoint.id')],
    },
    'access-connector': {
        'title': 'Databricks Access Connector',
        'description': 'Deploys a Databricks access connector for secure private access.',
        'resource_type': 'Microsoft.Databricks/workspaces/accessConnectors',
        'api_version': '2023-04-01',
        'name_template': "'${workspaceName}/${connectorName}'",
        'params': [
            ('workspaceName', 'string', 'databricks-portfolio', 'Existing Databricks workspace name'),
            ('connectorName', 'string', 'access-connector', 'Access connector name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('connectorId', 'string', 'accessConnector.id')],
    },
    'workspace': {
        'title': 'Databricks Workspace (Alternate)',
        'description': 'Deploys an Azure Databricks workspace for analytics and notebooks.',
        'resource_type': 'Microsoft.Databricks/workspaces',
        'api_version': '2023-04-01',
        'params': [
            ('workspaceName', 'string', 'databricks-portfolio', 'Databricks workspace name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('workspaceId', 'string', 'workspace.id')],
    },
    'management-lock': {
        'title': 'Management Lock',
        'description': 'Applies a management lock to protect resources from accidental deletion or modification.',
        'resource_type': 'Microsoft.Authorization/locks',
        'api_version': '2022-04-01',
        'params': [
            ('lockName', 'string', 'readOnlyLock', 'Lock name'),
            ('lockLevel', 'string', 'ReadOnly', 'Lock level'),
            ('notes', 'string', 'Protect resource', 'Lock notes'),
        ],
        'outputs': [('lockId', 'string', 'resourceLock.id')],
    },
    'policy-assignment': {
        'title': 'Policy Assignment',
        'description': 'Assigns an Azure Policy definition to a scope.',
        'resource_type': 'Microsoft.Authorization/policyAssignments',
        'api_version': '2022-01-01-preview',
        'params': [
            ('assignmentName', 'string', 'policyAssignment', 'Policy assignment name'),
            ('policyDefinitionId', 'string', '/subscriptions/.../providers/Microsoft.Authorization/policyDefinitions/...', 'Policy definition resource ID'),
            ('scope', 'string', resource_group().id if False else '/subscriptions/<subscriptionId>', 'Assignment scope'),
        ],
        'outputs': [('assignmentId', 'string', 'policyAssignment.id')],
    },
    'resource-group': {
        'title': 'Resource Group',
        'description': 'Deploys an Azure resource group.',
        'resource_type': 'Microsoft.Resources/resourceGroups',
        'api_version': '2021-04-01',
        'params': [
            ('resourceGroupName', 'string', 'rg-portfolio', 'Resource group name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('resourceGroupId', 'string', 'resourceGroup.id')],
    },
    'role-assignment': {
        'title': 'Role Assignment',
        'description': 'Creates an Azure RBAC role assignment for a principal.',
        'resource_type': 'Microsoft.Authorization/roleAssignments',
        'api_version': '2022-04-01-preview',
        'params': [
            ('principalId', 'string', '00000000-0000-0000-0000-000000000000', 'Principal object ID'),
            ('roleDefinitionId', 'string', '/subscriptions/.../providers/Microsoft.Authorization/roleDefinitions/...', 'Role definition ID'),
            ('scope', 'string', '/subscriptions/...', 'Assignment scope'),
        ],
        'outputs': [('roleAssignmentId', 'string', 'roleAssignment.id')],
    },
    'api-management': {
        'title': 'API Management Service',
        'description': 'Deploys an Azure API Management service instance.',
        'resource_type': 'Microsoft.ApiManagement/service',
        'api_version': '2022-08-01',
        'params': [
            ('serviceName', 'string', 'apim-portfolio', 'API Management service name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('publisherEmail', 'string', 'admin@example.com', 'Publisher email'),
            ('publisherName', 'string', 'Contoso', 'Publisher name'),
        ],
        'outputs': [('serviceId', 'string', 'apiManagementService.id')],
    },
    'apim-api': {
        'title': 'API Management API',
        'description': 'Deploys an API into an existing Azure API Management service.',
        'resource_type': 'Microsoft.ApiManagement/service/apis',
        'api_version': '2022-08-01',
        'name_template': "'${apiManagementName}/${apiName}'",
        'params': [
            ('apiManagementName', 'string', 'apim-portfolio', 'Existing API Management service name'),
            ('apiName', 'string', 'example-api', 'API name'),
            ('displayName', 'string', 'Example API', 'API display name'),
        ],
        'outputs': [('apiId', 'string', 'api.id')],
    },
    'apim-backend': {
        'title': 'API Management Backend',
        'description': 'Deploys an API Management backend as part of APIM configuration.',
        'resource_type': 'Microsoft.ApiManagement/service/backends',
        'api_version': '2022-08-01',
        'name_template': "'${apiManagementName}/${backendName}'",
        'params': [
            ('apiManagementName', 'string', 'apim-portfolio', 'Existing API Management service name'),
            ('backendName', 'string', 'backend-portfolio', 'Backend name'),
            ('backendUrl', 'string', 'https://example.com', 'Backend service URL'),
        ],
        'outputs': [('backendId', 'string', 'backend.id')],
    },
    'apim-named-value': {
        'title': 'API Management Named Value',
        'description': 'Deploys an API Management named value for configuration settings.',
        'resource_type': 'Microsoft.ApiManagement/service/namedValues',
        'api_version': '2022-08-01',
        'name_template': "'${apiManagementName}/${namedValueName}'",
        'params': [
            ('apiManagementName', 'string', 'apim-portfolio', 'Existing API Management service name'),
            ('namedValueName', 'string', 'example-value', 'Named value name'),
            ('value', 'string', 'example', 'Named value content'),
        ],
        'outputs': [('namedValueId', 'string', 'namedValue.id')],
    },
    'apim-policy': {
        'title': 'API Management Policy',
        'description': 'Deploys an API Management policy at the service scope.',
        'resource_type': 'Microsoft.ApiManagement/service/policies',
        'api_version': '2022-08-01',
        'name_template': "'${apiManagementName}/policy'",
        'params': [
            ('apiManagementName', 'string', 'apim-portfolio', 'Existing API Management service name'),
            ('policyContent', 'string', '<policies></policies>', 'APIM policy XML content'),
        ],
        'outputs': [('policyId', 'string', 'policy.id')],
    },
    'apim-product': {
        'title': 'API Management Product',
        'description': 'Deploys a product in Azure API Management.',
        'resource_type': 'Microsoft.ApiManagement/service/products',
        'api_version': '2022-08-01',
        'name_template': "'${apiManagementName}/${productName}'",
        'params': [
            ('apiManagementName', 'string', 'apim-portfolio', 'Existing API Management service name'),
            ('productName', 'string', 'starter', 'Product name'),
            ('displayName', 'string', 'Starter', 'Product display name'),
        ],
        'outputs': [('productId', 'string', 'product.id')],
    },
    'event-grid': {
        'title': 'Event Grid Topic',
        'description': 'Deploys an Azure Event Grid topic for event routing.',
        'resource_type': 'Microsoft.EventGrid/topics',
        'api_version': '2024-06-01',
        'params': [
            ('topicName', 'string', 'eventgrid-topic', 'Event Grid topic name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('topicId', 'string', 'eventGridTopic.id')],
    },
    'event-hub': {
        'title': 'Event Hubs Namespace',
        'description': 'Deploys an Azure Event Hubs namespace for streaming events.',
        'resource_type': 'Microsoft.EventHub/namespaces',
        'api_version': '2023-04-01',
        'params': [
            ('namespaceName', 'string', 'eventhub-namespace', 'Event Hubs namespace name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('namespaceId', 'string', 'eventHubNamespace.id')],
    },
    'logic-app': {
        'title': 'Logic App Workflow',
        'description': 'Deploys an Azure Logic Apps workflow.',
        'resource_type': 'Microsoft.Logic/workflows',
        'api_version': '2019-05-01',
        'params': [
            ('workflowName', 'string', 'logicapp-portfolio', 'Logic App workflow name'),
            ('location', 'string', 'eastus', 'Azure location'),
        ],
        'outputs': [('workflowId', 'string', 'logicApp.id')],
    },
    'service-bus': {
        'title': 'Service Bus Namespace',
        'description': 'Deploys an Azure Service Bus namespace for messaging workloads.',
        'resource_type': 'Microsoft.ServiceBus/namespaces',
        'api_version': '2023-05-01',
        'params': [
            ('namespaceName', 'string', 'sb-portfolio', 'Service Bus namespace name'),
            ('location', 'string', 'eastus', 'Azure location'),
            ('skuName', 'string', 'Standard', 'Service Bus SKU'),
        ],
        'outputs': [('namespaceId', 'string', 'serviceBusNamespace.id')],
    },
    'action-group': {
        'title': 'Action Group',
        'description': 'Deploys an Azure Monitor action group for alert notifications.',
        'resource_type': 'Microsoft.Insights/actionGroups',
        'api_version': '2022-06-15',
        'params': [
            ('actionGroupName', 'string', 'ag-portfolio', 'Action Group name'),
            ('shortName', 'string', 'ag', 'Action Group short name'),
        ],
        'outputs': [('actionGroupId', 'string', 'actionGroup.id')],
    },
    'activity-log-alert': {
        'title': 'Activity Log Alert',
        'description']: 'Deploys an Azure Activity Log Alert for subscription activity monitoring.',
        'resource_type': 'Microsoft.Insights/activityLogAlerts',
        'api_version': '2017-04-01',
        'params': [
            ('alertName', 'string', 'activityLogAlert', 'Activity log alert name'),
            ('scope', 'string', '/subscriptions/<subscriptionId>', 'Alert scope'),
        ],
        'outputs': [('alertId', 'string', 'activityLogAlert.id')],
    },
}
