apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sample-worker
spec:
  scaleTargetRef:
    name: sample-worker
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Manila
        start: "0 8 * * *"
        end: "0 18 * * *"
        desiredReplicas: "2"
