name: Deploy Helm to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm Deploy
        run: echo "aws eks update-kubeconfig && helm upgrade --install"
